### ISSUE TITLE
Where do you check the distortion metric in code?

### ISSUE THREAD

**Issue by SuperShinyEyes** [carlini/audio_adversarial_examples#11]
Hi Carlini, 

This isn't an issue but more of a question regarding your paper and your implementation.
In your paper your training objective is defined as,

![img_3ea67295efb3-1](https://user-images.githubusercontent.com/5738363/47624466-c4fd2f00-db25-11e8-892c-99b5ab297a8b.jpeg)

where the bottom distortion metric is __magnitude in perturbation(in decibel) relative to the source audio signal__. I couldn't find anywhere from `attack.py` where you check the inequality. How did you name "tau" variable in your code? 

Cheers,

**Comment by carlini** [comment]
I clip the distortion here

https://github.com/carlini/audio_adversarial_examples/blob/master/attack.py#L108
