### ISSUE TITLE
The Version of DeepSpeech?

### ISSUE THREAD

**Issue by 040840308** [carlini/audio_adversarial_examples#12]
Hi,

         What the correct version of DeepSpeech should be used? v0.1.1 or v0.1.0?
         In the install instructions, it maybe paradox.
         1. (cd DeepSpeech; git checkout tags/**v0.1.1**)
         2. Download the DeepSpeech model
         wget https://github.com/mozilla/DeepSpeech/releases/download/**v0.1.0**/deepspeech-0.1.0- 
         models.tar.gz tar -xzf deepspeech-0.1.0-models.tar.gz

         Thanks a lot.

**Comment by carlini** [comment]
Install 0.1.1. The model checkpoint 0.1.0 is what I used in the paper to do the eval.

**Comment by carlini** [comment]
(They are compatible)

**Comment by 040840308** [comment]
Thanks for so quick reply. I will reinstall 0.1.1.

**Comment by carlini** [comment]
0.1.0 should (I think) work too
