### ISSUE TITLE
List of dependencies

### ISSUE THREAD

**Issue by seansaito** [carlini/audio_adversarial_examples#13]
Hi, could you provide a list of dependencies (e.g. `requirements.txt`) for running the scripts? I see that one needs specific versions of libraries to produce results. Thanks.

**Comment by htZhang25** [comment]
Have you got the correct dependencies?

**Comment by carlini** [comment]
I just started from a clean virtualenv and found that `xdg` is causing issues. Do you have anything else that's not working right?

**Comment by zhang-wy15** [comment]
@carlini Hi, how can you solve the xdg issue when starting from a clean env? Is the xdg only used for setting default directory of checkpoint and summary files?
