### ISSUE TITLE
Code error?

### ISSUE THREAD

**Issue by 040840308** [carlini/audio_adversarial_examples#19]
Hi,

    In tf_logits.py, lines 39 and 40:
    # 2. windowing into frames of 320 samples, overlapping
    windowed = tf.stack([audio[:, i:i+400] for i in range(0,size-320,160)],1)
    
     Should the 400 be the frame size 320？ Is there any my misunderstanding about this?

     Thanks

**Comment by carlini** [comment]
I've updated the code to match deepspeech version 0.4.1; this should no longer be an issue.
