### ISSUE TITLE
Multiple input files?

### ISSUE THREAD

**Issue by EmpRamses** [carlini/audio_adversarial_examples#22]
I noticed that your code can get multiple input audio .wav files. But I have no idea how to set multiple files as input. Maybe you can update your README to give an example command.

**Comment by carlini** [comment]
Yeah, I should probably do that. For the time being, if you pass --in a.wav b.wav c.wav it will run the attack on all three of these files.

**Comment by EmpRamses** [comment]
Thanks, that's worked. Though my last project has been done, I think your code may be helpful in the next.
