### ISSUE TITLE
make_checkpoint.py

### ISSUE THREAD

**Issue by Librence** [carlini/audio_adversarial_examples#26]
ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
WARNING:tensorflow:From make_checkpoint.py:60: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.
Instructions for updating:
Please file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
i need your help!!

**Comment by carlini** [comment]
This file no longer exists; I've updated the code to work with deepspeech 0.4.1 and hopefully this should make life easier.
