### ISSUE TITLE
Attack not working?

### ISSUE THREAD

**Issue by iamgroot42** [carlini/audio_adversarial_examples#3]
I've tried the following for a couple of sentences/audio recordings now:

- Take an audio recording
- Run the attack with a target sentence (tried for a couple of sentences)
- Run the generated audio on the model which was used to run the attack

For all of the sentences I tried, none of the model's predictions matched the sentence which I had as the target while generating the perturbed audio. Am I missing something?

**Comment by carlini** [comment]
Can you confirm that it works on the .wav files from [here](https://nicholas.carlini.com/code/audio_adversarial_examples/commonvoice_subset.tgz)?

If it does work for those, and doesn't for your new recording, then my first guess would be that it's not sampled at 16KHz, and is instead 44.1 kHz.

**Comment by iamgroot42** [comment]
Well, I tried it for audio recordings of my own (sampled at 16KHz). Thanks to the assertion in the code, anything other than 16KHz will fail, so it's probably not because of the different sample rate. I will try it for these .wav files once

**Comment by iamgroot42** [comment]
I tried it for a couple of the sample recordings that you shared, and it's still not working. For instance, the second audio recording which originally says 'and you know it' when running on a perturbed version (with the target 'example'), produces the following prediction sequence:   

'dw lokd'

Something is seriously wrong here.

**Comment by billzo** [comment]
Are you sure that you're using the same pre-trained model for generation as for prediction? I've found that the results of generating adversarial examples against one model do not transfer to another model. Mozilla's model-0.1.0 has an md5sum of 08a9e6e8dc450007a0df0a37956bc795, but model-0.1.1 has an md5sum of 691edfc452f22c6b1d38d84f9be3c8e7.

I recommend checking this first.

**Comment by iamgroot42** [comment]
Yes @billzo, I am sure :) 
Checked the md5sum hash too, just to make sure.

P.S.: I do not have model-0.1.1, so not sure how that can even happen.

**Comment by carlini** [comment]
I am going to release a new version of the code today, first let's see if that fixes any issues and we can work from there.

**Comment by carlini** [comment]
I've pushed new code, hopefully this will fix any issues you have.
