### ISSUE TITLE
Setup Problem: pip3 install $(python3 util/taskcluster.py --decoder) gives errors

### ISSUE THREAD

**Issue by rogthlu** [carlini/audio_adversarial_examples#33]
In section 1 of the setup instructions - this line

pip3 install $(python3 util/taskcluster.py --decoder)

Fails. Giving either a 404 error (using a Python 3.6 environment) or an invalid wheel (using 3.7) error.

**Comment by tom-doerr** [comment]
I already created a pull request to fix the issue (https://github.com/carlini/audio_adversarial_examples/pull/31).
It has not been merged yet, but you can find the fixed version here: https://github.com/tom-doerr/audio_adversarial_examples
The fixed setup is quite different from the current setup, so do not hesitate to ask if something is unclear to you.

**Comment by rogthlu** [comment]
Got it working... somehow it was finding a whl at the url... so I downloaded by had, installed, and that seemed to fix it. Sorry that is (probably) not a robust fix; but managed to sort it.
