### ISSUE TITLE
How to set the correct the path for DeepSpeech in classify.py 

### ISSUE THREAD

**Issue by kkfkk** [carlini/audio_adversarial_examples#38]
File "classify.py", line 20, in <module>
    import DeepSpeech
ImportError: No module named 'DeepSpeech'

**Comment by carlini** [comment]
Could you give a bit more information? Did you follow the README and clone the DeepSpeech repository?

**Comment by kkfkk** [comment]
Hi Carlini, I use Tom's images installation and I did follow the steps you listed. When run step 5, there is the error that cannot find the DeepSpeech. Try to test if successfully installed. Thanks Carlini.
 /audio_adversarial_examples/DeepSpeech/audio_adversarial_examples-master# python3 classify.py --in sample-000000.wav --restore_path deepspeech-0.4.1-checkpoint/model.v0.4.1

**Comment by kkfkk** [comment]
Hi I copied the error. Many thanks
root@0f02665a6a91:/audio_adversarial_examples/DeepSpeech# ls
DeepSpeech.py                          data                     tc-lite_benchmark_model-ds-tests.sh
Dockerfile                             doc                      tc-node-tests-prod.sh
ISSUE_TEMPLATE.md                      evaluate.py              tc-node-tests.sh
LICENSE                                examples                 tc-python-tests-prod.sh
README.md                              images                   tc-python-tests.sh
RELEASE.md                             native_client            tc-schedule.sh
VERSION                                requirements.txt         tc-single-shot-inference.sh
__pycache__                            taskcluster              tc-tests-utils.sh
audio_adversarial_examples-master      tc-benchmark-tests.sh    tc-train-tests.sh
audio_adversarial_examples-master.zip  tc-brew-tests.sh         util
bazel.patch                            tc-cpp-ds-tests-prod.sh
bin                                    tc-cpp-ds-tests.sh
root@0f02665a6a91:/audio_adversarial_examples/DeepSpeech# cd audio_adversarial_examples-master
root@0f02665a6a91:/audio_adversarial_examples/DeepSpeech/audio_adversarial_examples-master# python3 classify.py --in sample-000000.wav --restore_path deepspeech-0.4.1-checkpoint/model.v0.4.1
Traceback (most recent call last):
  File "classify.py", line 20, in <module>
    import DeepSpeech
ImportError: No module named 'DeepSpeech'
root@0f02665a6a91:/audio_adversarial_examples/DeepSpeech/audio_adversarial_examples-master#

**Comment by tom-doerr** [comment]
Just so others know what we are talking about:
@kkfkk Tries to run the code with the docker images from my fork (https://github.com/tom-doerr/audio_adversarial_examples).

To me it looks like you are running the code in the wrong directory. I assume you cloned Nicholas Carlinis code inside the `/audio_adversarial_examples/DeepSpeech` directory. The issue with that is that `classify.py` looks for the `DeepSpeech` directory, but can't find it in the current directory `audio_adversarial_examples-master`. 
You don't need to clone Nicos code at all, my fork contains the newest versions of the files, so you should be able execute the code from within `/audio_adversarial_examples`.:
```
cd /audio_adversarial_examples
python3 classify.py --in sample-000000.wav --restore_path deepspeech-0.4.1-checkpoint/model.v0.4.1
```

**Comment by kkfkk** [comment]
@carlini @tom-doerr Hi guys, thanks for your help, I work it out now. I am planning use different attack methods in audio spoofing.

**Comment by carlini** [comment]
That's great. Thanks Tom for your help too.
