### ISSUE TITLE
Normal audio not correctly recognized by deepspeech

### ISSUE THREAD

**Issue by naiyeleo** [carlini/audio_adversarial_examples#4]
Hi, I try two audios from the project website. 

https://nicholas.carlini.com/code/audio_adversarial_examples/normal0.wav
https://nicholas.carlini.com/code/audio_adversarial_examples/adversarial0.wav

I download deepspeech model from `https://github.com/mozilla/DeepSpeech/releases/download/v0.1.0/deepspeech-0.1.0-models.tar.gz`
and install deepspeech using 
`pip3 install deepspeech-gpu`. 

When I check  thsese two audios against deepspeech, I find the adversarial example is recognized as `okay google browse to evil dot com` as intended but the normal audio is recognized as `wut thatthet dat asset the articues useless` instead of `without the dataset the article is useless`. 
Is there any part I did wrong?

**Comment by carlini** [comment]
Nope -- DeepSpeech isn't perfect at recognizing the normal phrases, it has some transcription errors.
