### ISSUE TITLE
scipy wavefile reading

### ISSUE THREAD

**Issue by ghost** [carlini/audio_adversarial_examples#6]
First, thanks for the code

I have trouble with dimensions numpy array named "audios" in attack.py

The code is trying to assign "audios" numpy array of dimension  [ 1 ,  868985, 2]  
to a tf variable of shape  [1, 868985 ]   ( shape of audios array has extra +2 dimension in the end ) 
in the attack.py

Maybe its the issue with scipy version ( wav.read )? . 

Could you take a look? or tell me what version of scipy you were using.

Thanks. :-)

**Comment by carlini** [comment]
The audio file should have a single channel. It looks like yours is stereo.
