### ISSUE TITLE
make_checkpoint.py not work

### ISSUE THREAD

**Issue by CHENTao-U** [carlini/audio_adversarial_examples#7]
Hi,

I have an issue when running make_checkpoint.py.
My environment is python3.5, tensorflow1.4, cuda8.0 and cudnn6.0.
When I running the python3 make_checkpoint.py, it shows the following errors:

DeepSpeech/util/audio.py:17: DeepSpeechDeprecationWarning: DeepSpeech Python bindings could not be imported, resorting to slower code to compute audio features. Refer to README.md for instructions on how to install (or build) the DeepSpeech Python bindings.
  category=DeepSpeechDeprecationWarning)
Traceback (most recent call last):
  File "make_checkpoint.py", line 51, in <module>
    DeepSpeech.initialize_globals()
  File "DeepSpeech/DeepSpeech.py", line 176, in initialize_globals
    FLAGS.ps_hosts = list(filter(len, FLAGS.ps_hosts.split(',')))
  File "/home/tao/.conda/envs/tensorflow-source/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 58, in __getattr__
    raise AttributeError(name)
AttributeError: ps_hosts

I guess the error maybe come from tensorflow, so I tried the pip installed and source installed, unfortunately, they didn't work either.

I have no idea about this attributeError, May I have your help?
Thanks.

**Comment by CHENTao-U** [comment]
Following the above issue,
I can run the deepspeech with the following command:

deepspeech models/output_graph.pb sample.wav models/alphabet.txt

and it shows correct result.

**Comment by carlini** [comment]
Ah I see, yeah, deepspeech updated their versions. I've updated the readme to indicate which version to use.

**Comment by JiajieZhang-Georgia** [comment]
I annotated the command as mentioned above,
but it gives me another error,
ValueError: Dimension must be 3 but is 4 for 'transpose' (op: 'Transpose') with input shapes: [?,?,?], [4].

Do you know how to solve it?
Thank you!

**Comment by carlini** [comment]
I've made a new issue for this #10.
