### ISSUE TITLE
What is `ERROR: The decoder library file does not exist.`?

### ISSUE THREAD

**Issue by SuperShinyEyes** [carlini/audio_adversarial_examples#9]
Hi Carlini,

I installed all the dependencies and downloaded the model from Mozilla. I think everything seems to work given that "Google take me to evil dot com" works.

However, when I run `python attack ....`, I get the following error:
```
ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
```
However, my code will run till the end and I get the right result.

__Is this something I should be worried about?__
It is related to DeepSpeech. According to [their instruction](https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md), this is literally for decoding the audio into text. 

Cheers,
Seyoung

**Comment by JiajieZhang-Georgia** [comment]
I got the same problem...
I wonder if you solved it?

**Comment by carlini** [comment]
This shouldn't actually be an issue. The decoder library is for using the language model, which I don't do for this attack. Everything should still work during attack generation.

Can you confirm for me that everything does work (both generating the adversarial examples and recognizing them)?

**Comment by SuperShinyEyes** [comment]
Hi! Thanks for the reply!
I managed to get it working for the “dataset” audio from your homepage.
However, when I try with my own audio data the audio becomes completely meaningless while DeepSpeech understands my target phrase. By meaningless I mean the output audio doesn’t contain any originality from the input. I have plotted the audio but I left my office already. I will share later.

**Comment by JiajieZhang-Georgia** [comment]
Hi, can I get a copy of you make_checkpoint.py?
@SuperShinyEyes 
I still can't pass it.
My email address is georgia.jjzhang@gmail.com

**Comment by carlini** [comment]
@SuperShinyEyes reported the issue was with the attack script. @JiajieZhang-Georgia are you having an issue with make_checkpoint? What does your error say? Can you create a new issue for that?

**Comment by SuperShinyEyes** [comment]
Good morning!

Here's the reference.
![sample](https://user-images.githubusercontent.com/5738363/46938852-7bb0d800-d06d-11e8-9e20-6dd2c041991a.png)
Here's the audio: https://www.dropbox.com/s/bkwww44ql5l1dqw/sample_audio_adversarial.wav?dl=0

Here's the adversarial. Notice the range is very small; [-0.001, 0.0001].
![adversarial](https://user-images.githubusercontent.com/5738363/46938851-7bb0d800-d06d-11e8-8bef-66eee2e210ee.png)
Here's the audio: https://www.dropbox.com/s/q63yk91ptnb6241/adversarial_days.wav?dl=0

Note that DeepSpeech still manages to detect the targetted phrase "and the day after the day after to morrow is monday"

My command to run the attack:
```
python3 attack.py --in sample.wav --target "And the day after the day after tomorrow is Monday" --out adversarial_days.wav
```

Have a lovely week!

**Comment by carlini** [comment]
Your input is not encoded as int16, after doing that it should work.

**Comment by SuperShinyEyes** [comment]
Yes, you were right. BTW can you validate if my audio conversion is done right? I'm new to audio.

```python
import librosa
import sys
import numpy as np
from scipy.io import wavfile

def convert_to_wav(path):
    '''
    Requirements for Attack:
        sample rate = 16000
        data type   = np.int16
    '''
    y, sr = librosa.core.load(path, sr=16000)
    # Set float32 to int16 range
    y = y * 32767
    new_path = path.split('.')[0] + '.wav'
    print("Exporting to ", new_path)
    wavfile.write('sample.wav', sr, y.astype(np.int16))

if __name__ == '__main__':
    assert len(sys.argv) > 1
    convert_to_wav(sys.argv[1])
```

**Comment by carlini** [comment]
Looks reasonable to me. I just convert them ahead of time with something like Audacity.

**Comment by TTTJJJWWW** [comment]
Same to me! When i run "python3 make_checkpoint.py", i get errors like that:

WARNING:tensorflow:From make_checkpoint.py:60: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.
Instructions for updating:
Please file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.
ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
This value should be small 0.0

what is the problem? and how to fix it?

**Comment by TTTJJJWWW** [comment]
@SuperShinyEyes Hi, did you get the error "ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter" when you run "python3 make_checkpoint.py"?

When i run "python3 make_checkpoint.py", this error occurs and computer will be frozen.

**Comment by SuperShinyEyes** [comment]
I don't recall having the same issue as you have. Try to install the dependencies using my Dockerfile: 
https://github.com/SuperShinyEyes/audio_adversarial_examples/blob/master/Dockerfile

**Comment by carlini** [comment]
This code doesn't need the language model. Everything should work fine without the decoder library file. When I get a chance today I'll silence that error.
